apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:yd+A53GS6HqEcwy3FIkNLZzlkiCXWRwYkcD8kMLSMQvlNaO1kV3Tdw==,iv:3SMvu5QLHci6YruUDwhBUihRHC5IlcejkBFv9RZW7Ys=,tag:k2PcO94xPR9axKucB74byw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q9cafe6ganwnnhmwtndu9jlxt8pt2s7lczqjawk569a6c8rzvcrs5z296g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWFRQNjdSd2FPOElNanhO
            RmFKVHF6ZkFtV1NuZ3FIeDd1VHB0OE4va2dBCkxVdHAzakRsUlFCTFNNV2VGTTk2
            REN3WG9VUEhmUGpZbXlIMVZaY0hMQWMKLS0tIEh4bVpjYlpCRk0wekgyeHpwRmZM
            aG9jTTIzdnh2RWhULzVBMER1MTdYOGcKl6rJmfyI2Q+GGAoISWkPr9rdANhVaU2v
            gymxT0hzyHx9NriCqgKMZBqPOVY6trBxEs3pnmA8ru7TDVJBwFHl9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-27T08:38:15Z"
    mac: ENC[AES256_GCM,data:w5Ghy0D5NPrlzr4UZ7LaA7vhmrp36MPubsar0fck14ydDkTwrVtpbXhdTLYjYDnOLlFL+RFfM+bDEWufFkn4ApgabNe8IrhuezBYwcEpJDPnN6w/aOQrrtr9FGu2CYljisLHdwdtkQ04eI5yOpZ8nZOLCvjhJTsauTcAKh+LXuU=,iv:thjpiniQtQgPrzbXTWh5haYXaL3X5RS8T7i/DwNohzU=,tag:GUWySirycQphiD2KtfYSjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
