apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:0mgEBqfEVFEvCmyINYTEMlASVsdr8iffOQcXF87vAEY5MHbhWaN18Q==,iv:Vgeao3y7XG/5As3bzKhz+cIelAVL7wi7+3z5M97j9ss=,tag:e1bm4dzHKpNk4V4S7H4uAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q9cafe6ganwnnhmwtndu9jlxt8pt2s7lczqjawk569a6c8rzvcrs5z296g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYStFenhZRTNPS1g3aHhQ
            RUtIM3drWnFQcDUrWDJTRktOMjhmSHZTNndFCkorMytSZGtyTFJFdlBtTUUvNUNC
            OEk5WUY5c2FjTGk2eHg5RkZ1SFVHRHMKLS0tIC9zUjVQbGJockJIWlAwRlZYbyt5
            aVV4eEFGOSs2QUc2Qkg5TkZKSldrUGcKah4+EmLPJMIkqSXth3SrUFqz6ROVJ63k
            GiQ85RmLGFwAHZ9EbwOJaWOf4w4EL+jnsAOqckTOGK3wfHZb9mpK/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-27T08:35:19Z"
    mac: ENC[AES256_GCM,data:E3vy21wYbZ5vFqIma91vQaULT9oVdWMLTxsEagpRgaKaMtt/Xv7F1lf9QzxSVcVOQV2BfFdP46BKu88/a+gdGiUWUVYIvgHgDddgO35UNtEdOJlzB0Q/swogeswPCHNCeEMHYVVliZ8TaEyhYA3o2mMa3VHtcdGSJ6lO7ar0PBg=,iv:yM26aztOpxxBQ+bVc0CaWg3N/vtyf9HUGAMd2gIOx7E=,tag:kooPJyncBwjft0j0/oCnXA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
