apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:4bXBn163vAw2,iv:imZDUo3U+SMCMKcKQugQih1dL12plX0aZFC8ks/R+ic=,tag:bi8LfVjIIkLN+ELUGXWjwg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:OVroYdoyClMm/0iAPAUnHGt/QR6f/6jJZA==,iv:tkFTVTX+BUgE3T3/n3OBYJ4Tz69gu/CQNg/zYFRU3NE=,tag:GlLpx0I9fxpqUQCcvTEsrQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:ZHfvyt9QeA/wYplJ3N9MkSrGRr1knQ7YuUgotlGGYyvNloat,iv:bA3f7Ux8aUAzB+wUu8z81I7uiV2F5wi+/KLWiYP0GNw=,tag:ovD2POnEpvhpezHobcPFVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q9cafe6ganwnnhmwtndu9jlxt8pt2s7lczqjawk569a6c8rzvcrs5z296g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOcC9wZ1dtK1IrSDhXSmVj
            MzBhWHZtdUJuK1I4emVyQU15bENKUjJ5cEZvCjQvTmZFRmZwOEplQlhydXFsVmlS
            SDIzUTVkdnRreUg5bTFLRno5cGRydTQKLS0tIGJMWkZuUDd4UVc2cC94Q2l6aUh0
            QU1oT0kzd2YvcE1ITWhvVVhGdStmQjAKGIWUxLjodVn2HWkVqaZqo1YdfZNVnvW7
            6xNBzPmxDTZEHefYgrgiitJuQu6I238cn9uVLQk0OoTCBfLdJ5dErg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-27T08:35:19Z"
    mac: ENC[AES256_GCM,data:pPyfU9TXpYeFmyttFR9jMOxsDCGFwEnn+tjqQPKXUqDcYQjV6VHyMD7EVB3sF8oEI37JYLaIgCEgGn5B00hGj3jSKi6uYaAx3Pzn67/w0IaIbqpMj4VZZUibkbApKrwK2ruh6yMpx+ItrtnlEaYxRayxslZDl0cLtylPKyHBqwg=,iv:m/aowl/Fw5Z+JD7sjd5DSwB9ocz5+gkVQ3/J7t1J3ok=,tag:5ENty7fFTdEA1IaCvduDSw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
