apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:GZKxg/MTQ+1tZvVChRT0sHzJqmm5PWeD1d9SnKV7WPt7EZ+Uss7BPQ==,iv:lMthys1Fb5nHXDip4iY9DtGjNcTwIvsaWIXEakzvwqo=,tag:U7ewl1UqBUr8E43rWd6xww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q9cafe6ganwnnhmwtndu9jlxt8pt2s7lczqjawk569a6c8rzvcrs5z296g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bmpmcVV4bHNLZEhVZ0x1
            V1VWZmJPZmx6QXFYZmNSVkRMSzFoTmQvWTJFCmRHeXFuK0dzSmtkS1FhRXZubEJp
            NHN4cVl3VStCRHYyVWVHQXVXZEZrT3cKLS0tIGlhSUhjdU4wWTVpUlFWQWt3UzBP
            bkZ0L3JqQk1iN3JTU3JoL0VLZWk2blUKfSIPvYBgMsPBWysuye4ahE/8YjESUCAq
            6uQ3mBDL4Nuk9vt84O4TMYWFkjU98vEIirbAFrwQjQsCL89/kOomaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-27T08:28:25Z"
    mac: ENC[AES256_GCM,data:2JBXxcJiiFEvlNxMUFVY4vpwjnSxrN2UXbdMll9sVeAsvG7bNXr4a4/r0DTp2jGreJZFzUyuBLQoPsAmslypRSFr6K1mJ02fE8ssmKqKvJgDo0mSDH5WhhBpTDTXqsHiJCojF7fpyUc+dbdlteUfdRJkWHUI1snk0vLo9cm/HK4=,iv:GyR5o4L6o2tnpG+AuFprqHwvFHlLxNEI6PbXCJm+vEo=,tag:hkeBIfqxlXXS8x9K+gNotQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
