apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:MJSYAaL88Jo8Emx/BoVUa/kZjBYI2SjLkrLS3R72Xwq02M5kFJyLPQ==,iv:jYVpHb8JeENvcXw3+AFw3kpGvtVFjebjufqv/+cd0/Q=,tag:Nr+AaERV4nMguF7srGu8jA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q9cafe6ganwnnhmwtndu9jlxt8pt2s7lczqjawk569a6c8rzvcrs5z296g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNd3NUdEx0NXNmaW9PalRa
            N282RW1uaWd3emxQeHo2M0ZSaUlVOEJRdzJFCm5iVnIvZkJ3TmRjREF4am9VRDJ3
            U0tYTmxseG4vRG5hVURlTXIzZjVDUmsKLS0tIHlGNlBKQlQrRVhFWCtiUFBxY2F2
            NzNIZzZtblRTNi9mWWx3VEE1UXhiY2cKHuuqn99Kn373Pal1w9QptjlPsXH+neUT
            oNMD0HecPMwCgQoXNmsw4kTQiRZn5xmi8khgF4lQrKbri3XOw+D7MA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-27T08:38:15Z"
    mac: ENC[AES256_GCM,data:2WxbS53fBXleiReVVWQULFXPZ3UVkCDwqF7CHCRxfumR1pfjdqPuyKVobGf2kXB7vEQNcLqJ77C5fK+S32znUiNorgYpC6RdgmVJMjkEKTz7JleqRAEVyteQiEou7FmGT/NeTQDuF1L3JJ8aY48oekMuwxC320P9cEN2gXJn7AY=,iv:72xRqP6F+PiMcEzRb11nm6yYrh/ROi9f2ygI43GSEE0=,tag:5IsLDHXvk50hm9ZX/fHi0w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
